from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.index, name='index'),
    path('catalog/', views.catalog_list, name='catalog_list'),
    path('catalog_create/', views.catalog_create, name='catalog_create'),
    path('upload_catalog/', views.upload_catalog, name='upload_catalog'),
    path('extract_catalog_data/<str:pk>/', views.extract_catalog_data, name='extract_catalog_data'),
    path('products/', views.products, name='products'),
    path('per_product/<str:pk>/', views.per_product, name='per_product'),
    path('each_product/<str:pk>/', views.each_product, name='each_product'),
    path("product_update/<int:pk>/", views.update, name="product_update"),
    path("delete/<int:pk>/", views.delete, name="product_delete"),
    path("add/", views.add_product, name="product_add"),
    path('marketing/', views.marketing, name='marketing'),
    path("dashboard/", views.dashboard, name="dashboard"),
    path('about/', views.about, name='about'),
    path('search/', views.search, name='search'),
    path('generate_sales_report/', views.generate_sales_report, name='generate_sales_report'),
    path('analyze-sales-data/', views.analyze_sales_data, name='analyze_sales_data'),
    path('subscription/', views.subscription, name='subscription'),
    path('send_bulk_emails/',views.send_bulk_emails, name='send_bulk_emails'),
    path('create_inventory/', views.create_inventory, name='create_inventory'),
    path('inventory_list/', views.inventory_list, name='inventory_list'),
    path('rate/', views.rate, name='rate'),
    path('rate_inventory/<int:inventory_id>/', views.rate_inventory, name='rate_inventory'),
    path('distributor/', views.distributor, name='distributor'),
    path('distributor_list/', views.distributor_list, name='distributor_list'),
    path('write_review/<int:pk>/', views.write_review, name='write_review'),
    path('delete_testimonial/<int:pk>/', views.delete_testimonial, name='delete_testimonial'),
    path('update_testimonial/<int:pk>/', views.update_testimonial, name='update_testimonial'),
    path('nearby_suppliers/', views.nearby_suppliers, name='nearby_suppliers'),
    path('each_catalog/<int:catalog_id>/', views.each_catalog, name='each_catalog'),
    path('analytics-tracker/', views.analytics_tracker, name='analytics_tracker'),
    path('logout/', views.logout_view, name='logout'),
]