# Generated by Django 5.0.3 on 2025-01-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_testimonial_rating_alter_distributor_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
        migrations.AddField(
            model_name='inventory',
            name='user_id',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
